name: Build Component in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/RDK*, develop ]

permissions:
  contents: read

jobs:
  build-rdk-libunpriv-on-pr:
    name: Build rdk-libunpriv component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: native build
        env:
          COVERITY_URL: ${{ secrets.COVERITY_URL }}
          COVERITY_STREAM: ${{ secrets.COVERITY_STREAM }}
          COVERITY_USER: ${{ secrets.COVERITY_USER }}
          COVERITY_PASSWORD: ${{ secrets.COVERITY_PASSWORD }}
        run: |
          chmod +x cov_build.sh
          sh -x cov_build.sh
